import '../models/dhikr_model.dart';

class LanguageInfo {
  final String code;
  final String name;
  final String nativeName;
  final String flag;
  final bool isRtl;

  const LanguageInfo({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.flag,
    this.isRtl = false,
  });
}

class LocalizationService {
  static const List<LanguageInfo> supportedLanguages = [
    LanguageInfo(code: 'tr', name: 'Türkçe', nativeName: 'Türkçe', flag: '🇹🇷'),
    LanguageInfo(code: 'ar', name: 'Arapça', nativeName: 'العربية', flag: '🇸🇦', isRtl: true),
    LanguageInfo(code: 'en', name: 'İngilizce', nativeName: 'English', flag: '🇬🇧'),
    LanguageInfo(code: 'ur', name: 'Urduca', nativeName: 'اردو', flag: '🇵🇰', isRtl: true),
    LanguageInfo(code: 'id', name: 'Endonezce', nativeName: 'Bahasa Indonesia', flag: '🇮🇩'),
    LanguageInfo(code: 'ms', name: 'Malayca', nativeName: 'Bahasa Melayu', flag: '🇲🇾'),
    LanguageInfo(code: 'fa', name: 'Farsça', nativeName: 'فارسی', flag: '🇮🇷', isRtl: true),
    LanguageInfo(code: 'ru', name: 'Rusça', nativeName: 'Русский', flag: '🇷🇺'),
    LanguageInfo(code: 'fr', name: 'Fransızca', nativeName: 'Français', flag: '🇫🇷'),
    LanguageInfo(code: 'de', name: 'Almanca', nativeName: 'Deutsch', flag: '🇩🇪'),
    LanguageInfo(code: 'it', name: 'İtalyanca', nativeName: 'Italiano', flag: '🇮🇹'),
  ];

  static bool isRtl(String langCode) {
    return langCode == 'ar' || langCode == 'ur' || langCode == 'fa';
  }

  static String get(String key, String lang) {
    final langDict = _translations[lang] ?? _translations['tr']!;
    return langDict[key] ?? _translations['tr']![key] ?? _translations['en']?[key] ?? key;
  }

  static String getDhikrTitle(DhikrModel dhikr, String lang) {
    if (dhikr.isCustom) return dhikr.title;
    final key = 'dhikr_${dhikr.id}_title';
    final res = get(key, lang);
    return res != key ? res : dhikr.title;
  }

  static String getDhikrMeaning(DhikrModel dhikr, String lang) {
    if (dhikr.isCustom) return dhikr.meaning;
    final key = 'dhikr_${dhikr.id}_meaning';
    final res = get(key, lang);
    return res != key ? res : dhikr.meaning;
  }

  static String getDhikrVirtue(DhikrModel dhikr, String lang) {
    if (dhikr.isCustom) return dhikr.virtue;
    final key = 'dhikr_${dhikr.id}_virtue';
    final res = get(key, lang);
    return res != key ? res : dhikr.virtue;
  }

  static String getCategoryName(String catKey, String lang) {
    final map = {
      'all': 'allCategories',
      'Namaz Tesbihatı': 'prayerTesbihat',
      'Günün Zikirleri': 'dailyDhikrCat',
      'Esmâ-ül Hüsnâ': 'esmaulHusna',
      'Özel Zikirler': 'customDhikrsCat',
      'Önemli Dualar': 'importantPrayers',
    };
    final transKey = map[catKey];
    if (transKey != null) {
      return get(transKey, lang);
    }
    return catKey;
  }

  static final Map<String, Map<String, String>> _translations = {
    // ----------------------------------------------------
    // 1. TÜRKÇE (tr)
    // ----------------------------------------------------
    'tr': {
      'appName': 'Huzur Zikirmatik',
      'tabCounter': 'Sayaç',
      'tabDhikrs': 'Zikirler',
      'tabQibla': 'Kıble',
      'tabHistory': 'Geçmiş',
      'tabSettings': 'Ayarlar',
      'qiblaHeading': 'Kıble Açısı',
      'facingQibla': 'Kâbe\'ye Doğruldunuz',
      'turnPhone': 'Telefonu Kıbleye Çevirin',
      'distanceToKaaba': 'Kâbe\'ye Mesafe',
      'selectCity': 'Şehir Seçin',
      'qiblaHint': 'Kıbleyi bulmak için telefonu düz tutun veya pusulayı parmağınızla çevirin.',
      'press': 'BAS',
      'goal': 'HEDEF',
      'free': 'SERBEST',
      'fullscreenOn': 'Tam Ekran Açık',
      'fullscreenOff': 'Tam Ekran Kapalı',
      'undo': '1 Azalt',
      'reset': 'Sıfırla',
      'sound': 'Ses',
      'vibration': 'Titreşim',
      'today': 'Bugün',
      'total': 'Toplam',
      'dailyActivity': 'Haftalık Devamlılık',
      'dayBreakdownTitle': 'Günlük Zikir Detayı',
      'dayTotal': 'Toplam Zikir',
      'topDhikrs': 'En Çok Çekilen Zikirler',
      'allCategories': 'Tümü',
      'prayerTesbihat': 'Namaz Tesbihatı',
      'dailyDhikrCat': 'Günün Zikirleri',
      'esmaulHusna': 'Esmâ-ül Hüsnâ',
      'customDhikrsCat': 'Özel Zikirler',
      'importantPrayers': 'Önemli Dualar',
      'addCustomDhikr': 'Yeni Zikir Ekle',
      'titleLabel': 'Zikir Başlığı *',
      'arabicLabel': 'Arapça Yazılışı (İsteğe Bağlı)',
      'targetLabel': 'Hedef Sayı',
      'meaningLabel': 'Anlamı veya Not (İsteğe Bağlı)',
      'addAndSelect': 'Ekle ve Seç',
      'cancel': 'İptal',
      'delete': 'Sil',
      'congratulations': 'Tebrikler! Maşâallâh',
      'targetReached': 'zikrini hedefine ulaştırdınız. Allah kabul eylesin.',
      'continueBtn': 'Devam Et',
      'resetConfirmTitle': 'Sayacı Sıfırla',
      'resetConfirmBody': 'Mevcut zikir sayacı sıfırlansın mı? Toplam sayı korunacaktır.',
      'language': 'Dil Seçeneği',
      'selectLanguage': 'Uygulama Dilini Seçin',
      'themeSelection': 'TEMA SEÇİMİ',
      'feedbackSettings': 'HİSSİYAT & GERİ BİLDİRİM',
      'usageSettings': 'KULLANIM TERCİHLERİ',
      'vibrationStrength': 'Titreşim Şiddeti',
      'clickSound': 'Tıklama Sesi',
      'milestoneVib': 'Hedefe Ulaşıldığında Özel Titreşim',
      'fullscreenMode': 'Tam Ekran Dokunma Modu',
      'privacyPolicy': 'Gizlilik Politikası',
      'about': 'Hakkında & Sürüm',
      'virtueAndMeaning': 'Fazileti ve Anlamı',
      'meaning': 'Anlamı:',
      'virtue': 'Fazileti:',
      'notSpecified': 'Belirtilmedi',
      'tapForDetails': 'Detay için dokun',
      'noDataForDate': 'Bu tarihte kayıtlı zikir bulunamadı.',
      'totalDhikrOnDate': 'Bu tarihte toplam {count} zikir çekildi.',
      'deleteConfirm': '"{name}" zikrini silmek istediğinize emin misiniz?',
      'themeEmerald': 'Zümrüt',
      'themeMidnight': 'Gece',
      'themeGold': 'Altın',
      'themeStone': 'Taş',
      'vibOff': 'Kapalı',
      'vibLight': 'Hafif',
      'vibMedium': 'Orta',
      'vibStrong': 'Güçlü',
      'change': 'Değiştir',
      'close': 'Kapat',
      'ok': 'Tamam',
      'aboutDesc': 'Modern, sade ve huzur veren dijital tesbihat uygulaması.',
      'privacyContent': 'Bu Zikirmatik uygulaması, kullanıcıların gizliliğine azami saygı göstermektedir.\n\n• Uygulama hiçbir kişisel veriyi, konumu veya kullanıcı bilgisini toplamaz veya üçüncü taraflarla paylaşmaz.\n• Tüm zikir sayaçları, ayarlar ve istatistikler yalnızca cihazınızın yerel hafızasında saklanır.\n• İnternet bağlantısı olmadan da %100 çevrimdışı ve güvenli bir şekilde çalışır.\n\nGoogle Play Store ve Apple App Store gizlilik standartları ile tam uyumludur.',
      // Dhikrs
      'dhikr_subhanallah_title': 'Sübhanallâh',
      'dhikr_subhanallah_meaning': 'Allah her türlü noksan ve eksik sıfatlardan münezzehtir.',
      'dhikr_subhanallah_virtue': 'Peygamberimiz (s.a.v.): "Her namazdan sonra 33 defa Sübhanallah diyenin günahları deniz köpüğü kadar da olsa bağışlanır."',
      'dhikr_elhamdulillah_title': 'Elhamdülillâh',
      'dhikr_elhamdulillah_meaning': 'Hamd ve övgülerin tamamı sadece Allah\'a aittir.',
      'dhikr_elhamdulillah_virtue': '"Elhamdülillâh mizanı doldurur." Şükür ve manevi huzur için en faziletli zikirlerdendir.',
      'dhikr_allahu_ekber_title': 'Allâh-u Ekber',
      'dhikr_allahu_ekber_meaning': 'Allah en büyüktür, O\'nun azametine denk hiçbir şey yoktur.',
      'dhikr_allahu_ekber_virtue': 'Kalpteki vesveseleri yok eder, kula Allah\'ın sonsuz kudretini hatırlatır.',
      'dhikr_kelime_i_tevhid_title': 'Lâ ilâhe illallâh',
      'dhikr_kelime_i_tevhid_meaning': 'Allah\'tan başka ilah yoktur.',
      'dhikr_kelime_i_tevhid_virtue': 'Zikrin en faziletlisidir. Kalbi arındırır, imanı tazeler ve cennetin anahtarıdır.',
      'dhikr_estagfirullah_title': 'Estağfirullâh el-Azîm',
      'dhikr_estagfirullah_meaning': 'Yüce Allah\'tan bağışlanma diliyorum.',
      'dhikr_estagfirullah_virtue': 'Rızkı bollaştırır, dert ve kederleri giderir, kalpteki manevi pası temizler.',
      'dhikr_salavat_title': 'Salavât-ı Şerîfe',
      'dhikr_salavat_meaning': 'Allah\'ım! Efendimiz Hz. Muhammed\'e rahmet ve selam eyle.',
      'dhikr_salavat_virtue': '"Bana bir defa salavat getirene Allah on defa rahmet eder, on günahını siler."',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'Sübhanallâhi ve Bihamdihî',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'Allah\'ı hamd ile tesbih ederim.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': 'Günde 100 defa söyleyenin günahları deniz köpüğü kadar da olsa dökülür.',
      'dhikr_la_havle_title': 'Lâ Havle Ve Lâ Kuvvete İllâ Billâh',
      'dhikr_la_havle_meaning': 'Güç ve kuvvet ancak şanı yüce olan Allah\'a aittir.',
      'dhikr_la_havle_virtue': 'Cennet hazinelerinden bir hazinedir; çaresizlik ve sıkıntı anlarında ferahlık vesilesidir.',
      'dhikr_hasbunallah_title': 'Hasbünallâhu ve Ni\'mel Vekîl',
      'dhikr_hasbunallah_meaning': 'Allah bize yeter, O ne güzel vekildir.',
      'dhikr_hasbunallah_virtue': 'Hz. İbrahim ateşe atılırken bu zikri söylemiştir. Korku ve kaygıda en büyük sığınaktır.',
      'dhikr_ya_allah_title': 'Yâ Allâh (Celle Celâluhû)',
      'dhikr_ya_allah_meaning': 'Tüm isim ve sıfatları kendinde toplayan Zat-ı Zülcelal.',
      'dhikr_ya_allah_virtue': 'Günde 1000 defa zikreden kimsenin kalbi nurlanır ve basireti açılır.',
    },

    // ----------------------------------------------------
    // 2. ARAPÇA (ar)
    // ----------------------------------------------------
    'ar': {
      'appName': 'مسبحة الهدوء',
      'tabCounter': 'المسبحة',
      'tabDhikrs': 'الأذكار',
      'tabQibla': 'القبلة',
      'tabHistory': 'السجل',
      'tabSettings': 'الإعدادات',
      'qiblaHeading': 'اتجاه القبلة',
      'facingQibla': 'أنت باتجاه الكعبة المشرفة',
      'turnPhone': 'أدر هاتفك باتجاه القبلة',
      'distanceToKaaba': 'المسافة إلى الكعبة',
      'selectCity': 'اختر المدينة',
      'qiblaHint': 'ضع الهاتف مستوياً للحصول على أفضل دقة.',
      'press': 'اضغط',
      'goal': 'الهدف',
      'free': 'حر',
      'fullscreenOn': 'ملء الشاشة مفعل',
      'fullscreenOff': 'ملء الشاشة معطل',
      'undo': 'إنقاص 1',
      'reset': 'إعادة ضبط',
      'sound': 'الصوت',
      'vibration': 'الاهتزاز',
      'today': 'اليوم',
      'total': 'المجموع',
      'dailyActivity': 'المتابعة الأسبوعية',
      'dayBreakdownTitle': 'تفاصيل أذكار اليوم',
      'dayTotal': 'إجمالي الأذكار',
      'topDhikrs': 'الأذكار الأكثر تسبيحاً',
      'allCategories': 'الكل',
      'prayerTesbihat': 'تسبيحات الصلاة',
      'dailyDhikrCat': 'أذكار اليوم',
      'esmaulHusna': 'أسماء الله الحسنى',
      'customDhikrsCat': 'أذكاري الخاصة',
      'importantPrayers': 'أدعية مهمة',
      'addCustomDhikr': 'إضافة ذكر جديد',
      'titleLabel': 'عنوان الذكر *',
      'arabicLabel': 'النص العربي',
      'targetLabel': 'العدد المستهدف',
      'meaningLabel': 'المعنى أو ملاحظات',
      'addAndSelect': 'إضافة واختيار',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'congratulations': 'تهانينا! ما شاء الله',
      'targetReached': 'لقد أتممت هذا الذكر بنجاح. تقبل الله منك.',
      'continueBtn': 'متابعة',
      'resetConfirmTitle': 'إعادة تعيين العداد',
      'resetConfirmBody': 'هل ترغب في تصفير العداد الحالي؟ سيبقى الإجمالي محفوظاً.',
      'language': 'اللغة',
      'selectLanguage': 'اختر لغة التطبيق',
      'themeSelection': 'اختيار المظهر',
      'feedbackSettings': 'الاهتزاز والصوت',
      'usageSettings': 'تفضيلات الاستخدام',
      'vibrationStrength': 'قوة الاهتزاز',
      'clickSound': 'صوت النقر',
      'milestoneVib': 'اهتزاز خاص عند اكتمال الهدف',
      'fullscreenMode': 'وضع النقر في أي مكان بالشاشة',
      'privacyPolicy': 'سياسة الخصوصية',
      'about': 'حول التطبيق والإصدار',
      'virtueAndMeaning': 'الفضيلة والمعنى',
      'meaning': 'المعنى:',
      'virtue': 'الفضيلة:',
      'notSpecified': 'غير محدد',
      'tapForDetails': 'انقر للتفاصيل',
      'noDataForDate': 'لا يوجد ذكر مسجل في هذا التاريخ.',
      'totalDhikrOnDate': 'تم تسجيل {count} ذكر في هذا التاريخ.',
      'deleteConfirm': 'هل أنت متأكد من حذف الذكر "{name}"؟',
      'themeEmerald': 'زمردي',
      'themeMidnight': 'ليلي',
      'themeGold': 'ذهبي',
      'themeStone': 'حجري',
      'vibOff': 'إيقاف',
      'vibLight': 'خفيف',
      'vibMedium': 'متوسط',
      'vibStrong': 'قوي',
      'change': 'تغيير',
      'close': 'إغلاق',
      'ok': 'حسناً',
      'aboutDesc': 'تطبيق مسبحة وأذكار رقمية إسلامية حديثة وأنيقة.',
      'privacyContent': 'يحترم هذا التطبيق خصوصيتك بالكامل:\n• لا يتم جمع أي بيانات شخصية أو موقع أو معلومات مستخدم.\n• جميع العدادات والإحصائيات محفوظة محلياً فقط على جهازك.\n• يعمل بنسبة 100% بدون إنترنت بأمان تام.',
      // Dhikrs
      'dhikr_subhanallah_title': 'سبحان الله',
      'dhikr_subhanallah_meaning': 'تنزيه الله تعالى عن كل نقص وعيب.',
      'dhikr_subhanallah_virtue': 'قال رسول الله ﷺ: "من سبح دبر كل صلاة ثلاثاً وثلاثين... غفرت خطاياه وإن كانت مثل زبد البحر".',
      'dhikr_elhamdulillah_title': 'الحمد لله',
      'dhikr_elhamdulillah_meaning': 'الثناء التام والمطلق لله رب العالمين.',
      'dhikr_elhamdulillah_virtue': 'الحمد لله تملأ الميزان، وهي من أعظم الأذكار شكراً لله وطلباً للسكينة.',
      'dhikr_allahu_ekber_title': 'الله أكبر',
      'dhikr_allahu_ekber_meaning': 'الله أجلّ وأعظم من كل شيء في الوجود.',
      'dhikr_allahu_ekber_virtue': 'تطرد وساوس النفس والشيطان وتملأ القلب بهيبة الله وجلاله.',
      'dhikr_kelime_i_tevhid_title': 'لا إله إلا الله',
      'dhikr_kelime_i_tevhid_meaning': 'لا معبود بحق إلا الله وحده لا شريك له.',
      'dhikr_kelime_i_tevhid_virtue': 'أفضل الذكر لا إله إلا الله، مفتاح الجنة وعماد الإيمان.',
      'dhikr_estagfirullah_title': 'أستغفر الله العظيم',
      'dhikr_estagfirullah_meaning': 'طلب المغفرة والستر والعفو من الله العظيم.',
      'dhikr_estagfirullah_virtue': 'يجلب الرزق، يفرج الكروب، ويطهر القلب من الذنوب.',
      'dhikr_salavat_title': 'اللهم صل على محمد',
      'dhikr_salavat_meaning': 'الصلاة والسلام على نبينا محمد وعلى آله وصحبه.',
      'dhikr_salavat_virtue': 'من صلى علي واحدة صلى الله عليه بها عشراً.',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'سبحان الله وبحمده',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'تسبيح الله وحمده والثناء عليه.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': 'من قالها مائة مرة حُطت خطاياه وإن كانت مثل زبد البحر.',
      'dhikr_la_havle_title': 'لا حول ولا قوة إلا بالله',
      'dhikr_la_havle_meaning': 'لا تحول عن معصية ولا قوة على طاعة إلا بتوفيق الله.',
      'dhikr_la_havle_virtue': 'كنز من كنوز الجنة، دواء لتسعة وتسعين داء أيسرها الهم.',
      'dhikr_hasbunallah_title': 'حسبنا الله ونعم الوكيل',
      'dhikr_hasbunallah_meaning': 'الله كافينا وهو نعم المولى ونعم النصير.',
      'dhikr_hasbunallah_virtue': 'قالها إبراهيم عليه السلام حين أُلقي في النار، ملاذ المؤمن في الشدائد.',
      'dhikr_ya_allah_title': 'يا الله (جل جلاله)',
      'dhikr_ya_allah_meaning': 'الاسم الجامع لجميع الأسماء والصفات الإلهية.',
      'dhikr_ya_allah_virtue': 'ينير القلوب ويمنح الطمأنينة ويزيد البصيرة.',
    },

    // ----------------------------------------------------
    // 3. İNGİLİZCE (en)
    // ----------------------------------------------------
    'en': {
      'appName': 'Serenity Tasbeeh',
      'tabCounter': 'Counter',
      'tabDhikrs': 'Dhikrs',
      'tabQibla': 'Qibla',
      'tabHistory': 'History',
      'tabSettings': 'Settings',
      'qiblaHeading': 'Qibla Direction',
      'facingQibla': 'Facing Holy Kaaba',
      'turnPhone': 'Rotate phone towards Qibla',
      'distanceToKaaba': 'Distance to Kaaba',
      'selectCity': 'Select City',
      'qiblaHint': 'Hold phone flat or rotate compass to align with the Qibla needle.',
      'press': 'TAP',
      'goal': 'GOAL',
      'free': 'FREE',
      'fullscreenOn': 'Fullscreen On',
      'fullscreenOff': 'Fullscreen Off',
      'undo': '-1 Count',
      'reset': 'Reset',
      'sound': 'Sound',
      'vibration': 'Vibration',
      'today': 'Today',
      'total': 'Total',
      'dailyActivity': 'Weekly Consistency',
      'dayBreakdownTitle': 'Daily Dhikr Breakdown',
      'dayTotal': 'Total Dhikrs',
      'topDhikrs': 'Most Recited Dhikrs',
      'allCategories': 'All',
      'prayerTesbihat': 'Prayer Tasbeeh',
      'dailyDhikrCat': 'Daily Dhikrs',
      'esmaulHusna': 'Names of Allah',
      'customDhikrsCat': 'Custom Dhikrs',
      'importantPrayers': 'Key Prayers',
      'addCustomDhikr': 'Add New Dhikr',
      'titleLabel': 'Dhikr Title *',
      'arabicLabel': 'Arabic Text (Optional)',
      'targetLabel': 'Target Count',
      'meaningLabel': 'Meaning / Notes (Optional)',
      'addAndSelect': 'Add & Select',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'congratulations': 'MashaAllah! Congratulations',
      'targetReached': 'You have completed the target for this dhikr. May Allah accept.',
      'continueBtn': 'Continue',
      'resetConfirmTitle': 'Reset Counter',
      'resetConfirmBody': 'Are you sure you want to reset the current counter? Total lifetime count is preserved.',
      'language': 'Language',
      'selectLanguage': 'Select Application Language',
      'themeSelection': 'THEME SELECTION',
      'feedbackSettings': 'SENSORY & FEEDBACK',
      'usageSettings': 'PREFERENCES',
      'vibrationStrength': 'Vibration Strength',
      'clickSound': 'Click Sound Effect',
      'milestoneVib': 'Special Vibration on Goal',
      'fullscreenMode': 'Fullscreen Tap Mode',
      'privacyPolicy': 'Privacy Policy',
      'about': 'About & Version',
      'virtueAndMeaning': 'Virtue and Meaning',
      'meaning': 'Meaning:',
      'virtue': 'Virtue:',
      'notSpecified': 'Not specified',
      'tapForDetails': 'Tap for details',
      'noDataForDate': 'No dhikrs recorded on this date.',
      'totalDhikrOnDate': 'A total of {count} dhikrs were recited on this date.',
      'deleteConfirm': 'Are you sure you want to delete "{name}"?',
      'themeEmerald': 'Emerald',
      'themeMidnight': 'Midnight',
      'themeGold': 'Gold',
      'themeStone': 'Stone',
      'vibOff': 'Off',
      'vibLight': 'Light',
      'vibMedium': 'Medium',
      'vibStrong': 'Strong',
      'change': 'Change',
      'close': 'Close',
      'ok': 'OK',
      'aboutDesc': 'Modern, minimalist, and serene digital tasbeeh application.',
      'privacyContent': 'This application values your privacy above all:\n• No personal data, location, or usage habits are collected or shared.\n• All counts, statistics, and settings are stored locally on your device.\n• Operates 100% offline with zero external network tracking.',
      // Dhikrs
      'dhikr_subhanallah_title': 'SubhanAllah',
      'dhikr_subhanallah_meaning': 'Glory be to Allah, free from all imperfections.',
      'dhikr_subhanallah_virtue': 'The Prophet ﷺ said: "Whoever glorifies Allah 33 times after every prayer, his sins will be forgiven even if like the foam of the sea."',
      'dhikr_elhamdulillah_title': 'Alhamdulillah',
      'dhikr_elhamdulillah_meaning': 'All praise and gratitude belong to Allah alone.',
      'dhikr_elhamdulillah_virtue': '"Alhamdulillah fills the scale." Essential for gratitude and tranquility.',
      'dhikr_allahu_ekber_title': 'Allahu Akbar',
      'dhikr_allahu_ekber_meaning': 'Allah is the Greatest, supreme above all creation.',
      'dhikr_allahu_ekber_virtue': 'Dispels inner anxiety and instills reverence for Allah\'s majesty.',
      'dhikr_kelime_i_tevhid_title': 'La ilaha illallah',
      'dhikr_kelime_i_tevhid_meaning': 'There is no god worthy of worship except Allah.',
      'dhikr_kelime_i_tevhid_virtue': 'The best form of remembrance, the pillar of faith and key to Paradise.',
      'dhikr_estagfirullah_title': 'Astaghfirullah Al-Azeem',
      'dhikr_estagfirullah_meaning': 'I seek forgiveness from Allah, the Magnificent.',
      'dhikr_estagfirullah_virtue': 'Expands sustenance, relieves distress, and purifies the spiritual heart.',
      'dhikr_salavat_title': 'Salawat upon the Prophet',
      'dhikr_salavat_meaning': 'O Allah, send blessings and peace upon our Master Muhammad.',
      'dhikr_salavat_virtue': '"Whoever sends blessings upon me once, Allah sends blessings upon him tenfold."',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'SubhanAllahi wa Bihamdihi',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'Glory be to Allah and His is the praise.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': 'Recited 100 times a day, sins are forgiven even if as vast as sea foam.',
      'dhikr_la_havle_title': 'La Hawla wa La Quwwata illa Billah',
      'dhikr_la_havle_meaning': 'There is no power nor strength except through Allah.',
      'dhikr_la_havle_virtue': 'A treasure from the treasures of Paradise; a remedy for sorrow and hardship.',
      'dhikr_hasbunallah_title': 'Hasbunallahu wa Ni\'mal Wakeel',
      'dhikr_hasbunallah_meaning': 'Allah is sufficient for us, and He is the best Disposer of affairs.',
      'dhikr_hasbunallah_virtue': 'Said by Prophet Ibrahim (AS) when thrown into the fire. The ultimate reliance on God.',
      'dhikr_ya_allah_title': 'Ya Allah (Jalla Jalaluhu)',
      'dhikr_ya_allah_meaning': 'The Greatest Divine Name encompassing all perfect attributes.',
      'dhikr_ya_allah_virtue': 'Illuminates the inner soul and grants spiritual perception.',
    },

    // ----------------------------------------------------
    // 4. URDUCA (ur)
    // ----------------------------------------------------
    'ur': {
      'appName': 'سکون تسبیح',
      'tabCounter': 'تسبیح',
      'tabDhikrs': 'اذکار',
      'tabHistory': 'ریکارڈ',
      'tabSettings': 'ترتیبات',
      'press': 'دبائیں',
      'goal': 'ہدف',
      'free': 'کھلا',
      'fullscreenOn': 'فل سکرین آن',
      'fullscreenOff': 'فل سکرین آف',
      'undo': '1 کم کریں',
      'reset': 'ری سیٹ',
      'sound': 'آواز',
      'vibration': 'وائبریشن',
      'today': 'آج',
      'total': 'کل تعداد',
      'dailyActivity': 'ہفتہ وار ریکارڈ',
      'dayBreakdownTitle': 'یومیہ تفصیلات',
      'dayTotal': 'کل اذکار',
      'topDhikrs': 'کثرت سے پڑھے جانے والے اذکار',
      'allCategories': 'تمام',
      'prayerTesbihat': 'نماز کی تسبیحات',
      'dailyDhikrCat': 'روزمرہ اذکار',
      'esmaulHusna': 'اسمائے حسنیٰ',
      'customDhikrsCat': 'ذاتی اذکار',
      'importantPrayers': 'اہم دعائیں',
      'addCustomDhikr': 'نیا ذکر شامل کریں',
      'titleLabel': 'عنوان *',
      'arabicLabel': 'عربی عبارت',
      'targetLabel': 'ہدف کی تعداد',
      'meaningLabel': 'معنی یا نوٹ',
      'addAndSelect': 'شامل کریں',
      'cancel': 'منسوخ',
      'delete': 'حذف',
      'congratulations': 'مبارک ہو! ماشاء اللہ',
      'targetReached': 'آپ نے اپنا ہدف مکمل کر لیا ہے۔ اللہ قبول فرمائے۔',
      'continueBtn': 'جاری رکھیں',
      'resetConfirmTitle': 'ری سیٹ کریں',
      'resetConfirmBody': 'کیا آپ موجودہ کاؤنٹر ری سیٹ کرنا چاہتے ہیں؟',
      'language': 'زبان',
      'selectLanguage': 'زبان کا انتخاب کریں',
      'themeSelection': 'تھیم کا انتخاب',
      'feedbackSettings': 'آواز اور وائبریشن',
      'usageSettings': 'ترجیحات',
      'vibrationStrength': 'وائبریشن کی شدت',
      'clickSound': 'کلک کی آواز',
      'milestoneVib': 'ہدف پر وائبریشن',
      'fullscreenMode': 'فل سکرین ٹیپ موڈ',
      'privacyPolicy': 'پرائیویسی پالیسی',
      'about': 'ایپ کے بارے میں',
      'virtueAndMeaning': 'فضیلت اور معنی',
      'meaning': 'معنی:',
      'virtue': 'فضیلت:',
      'notSpecified': 'درج نہیں',
      'tapForDetails': 'تفصیل کے لیے کلک کریں',
      'noDataForDate': 'اس تاریخ کا کوئی ذکر موجود نہیں ہے۔',
      'totalDhikrOnDate': 'اس تاریخ کو کل {count} اذکار پڑھے گئے۔',
      'deleteConfirm': 'کیا آپ "{name}" کو حذف کرنا چاہتے ہیں؟',
      'themeEmerald': 'زمرد',
      'themeMidnight': 'رات',
      'themeGold': 'سنہری',
      'themeStone': 'پتھر',
      'vibOff': 'بند',
      'vibLight': 'ہلکا',
      'vibMedium': 'درمیانہ',
      'vibStrong': 'تیز',
      'change': 'تبدیل کریں',
      'close': 'بند کریں',
      'ok': 'ٹھیک ہے',
      'aboutDesc': 'ایک خوبصورت، پرسکون اور جدید ڈیجیٹل تسبیح ایپ۔',
      'privacyContent': 'یہ تسبیح ایپ مکمل رازداری کی ضمانت دیتی ہے۔ کوئی ذاتی ڈیٹا جمع نہیں کیا جاتا اور یہ مکمل آف لائن کام کرتی ہے۔',
      // Dhikrs
      'dhikr_subhanallah_title': 'سبحان اللہ',
      'dhikr_subhanallah_meaning': 'اللہ ہر عیب اور نقص سے پاک ہے۔',
      'dhikr_subhanallah_virtue': 'نماز کے بعد 33 بار پڑھنے والے کے گناہ سمندر کے جھاگ کے برابر بھی ہوں تو بخش دیے جاتے ہیں۔',
      'dhikr_elhamdulillah_title': 'الحمد للہ',
      'dhikr_elhamdulillah_meaning': 'تمام تعریفیں صرف اللہ ہی کے لیے ہیں۔',
      'dhikr_elhamdulillah_virtue': 'الحمد للہ میزان کو نیکیوں سے بھر دیتا ہے۔',
      'dhikr_allahu_ekber_title': 'اللہ اکبر',
      'dhikr_allahu_ekber_meaning': 'اللہ سب سے بڑا ہے۔',
      'dhikr_allahu_ekber_virtue': 'دل کو سکون بخشتا ہے اور تکبر کو مٹاتا ہے۔',
      'dhikr_kelime_i_tevhid_title': 'لا الہ الا اللہ',
      'dhikr_kelime_i_tevhid_meaning': 'اللہ کے سوا کوئی معبود نہیں۔',
      'dhikr_kelime_i_tevhid_virtue': 'سب سے افضل ذکر ہے، جنت کی کنجی ہے۔',
      'dhikr_estagfirullah_title': 'استغفر اللہ العظیم',
      'dhikr_estagfirullah_meaning': 'میں عظمت والے اللہ سے بخشش مانگتا ہوں۔',
      'dhikr_estagfirullah_virtue': 'رزق میں برکت اور پریشانیوں سے نجات کا ذریعہ ہے۔',
      'dhikr_salavat_title': 'درود شریف',
      'dhikr_salavat_meaning': 'اے اللہ! ہمارے نبی محمد ﷺ پر رحمت اور سلامتی نازل فرما۔',
      'dhikr_salavat_virtue': 'ایک بار درود بھیجنے پر اللہ دس رحمتیں نازل فرماتا ہے۔',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'سبحان اللہ وبحمدہ',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'اللہ پاک ہے اپنی تعریف کے ساتھ۔',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': 'روزانہ 100 بار پڑھنے سے تمام صغیرہ گناہ معاف ہو جاتے ہیں۔',
      'dhikr_la_havle_title': 'لا حول ولا قوۃ الا باللہ',
      'dhikr_la_havle_meaning': 'گناہوں سے بچنے اور نیکی کرنے کی طاقت صرف اللہ کی مدد سے ہے۔',
      'dhikr_la_havle_virtue': 'جنت کے خزانوں میں سے ایک خزانہ ہے۔',
      'dhikr_hasbunallah_title': 'حسبنا اللہ ونعم الوکیل',
      'dhikr_hasbunallah_meaning': 'ہمیں اللہ کافی ہے اور وہ بہترین کارساز ہے۔',
      'dhikr_hasbunallah_virtue': 'مشکل وقت اور خوف میں سب سے بڑا سہارا ہے۔',
      'dhikr_ya_allah_title': 'یا اللہ (جل جلالہ)',
      'dhikr_ya_allah_meaning': 'اللہ کا اسم اعظم جو تمام صفات کا جامع ہے۔',
      'dhikr_ya_allah_virtue': 'دل کو نورانی بناتا ہے اور بصیرت عطا کرتا ہے۔',
    },

    // ----------------------------------------------------
    // 5. ENDONEZCE (id)
    // ----------------------------------------------------
    'id': {
      'appName': 'Tasbih Ketenangan',
      'tabCounter': 'Hitung',
      'tabDhikrs': 'Zikir',
      'tabHistory': 'Riwayat',
      'tabSettings': 'Pengaturan',
      'press': 'TEKAN',
      'goal': 'TARGET',
      'free': 'BEBAS',
      'fullscreenOn': 'Layar Penuh Aktif',
      'fullscreenOff': 'Layar Penuh Nonaktif',
      'undo': 'Kurang 1',
      'reset': 'Reset',
      'sound': 'Suara',
      'vibration': 'Getaran',
      'today': 'Hari Ini',
      'total': 'Total',
      'dailyActivity': 'Aktivitas Mingguan',
      'dayBreakdownTitle': 'Rincian Zikir Harian',
      'dayTotal': 'Total Zikir',
      'topDhikrs': 'Zikir Paling Sering',
      'allCategories': 'Semua',
      'prayerTesbihat': 'Tasbih Shalat',
      'dailyDhikrCat': 'Zikir Harian',
      'esmaulHusna': 'Asmaul Husna',
      'customDhikrsCat': 'Zikir Khusus',
      'importantPrayers': 'Doa Penting',
      'addCustomDhikr': 'Tambah Zikir Baru',
      'titleLabel': 'Judul Zikir *',
      'arabicLabel': 'Tulisan Arab (Opsional)',
      'targetLabel': 'Target Hitungan',
      'meaningLabel': 'Arti / Catatan',
      'addAndSelect': 'Tambah & Pilih',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'congratulations': 'MasyaAllah! Selamat',
      'targetReached': 'Anda telah mencapai target zikir ini. Semoga Allah menerima.',
      'continueBtn': 'Lanjutkan',
      'resetConfirmTitle': 'Reset Hitungan',
      'resetConfirmBody': 'Apakah Anda yakin ingin mengatur ulang hitungan saat ini?',
      'language': 'Pilihan Bahasa',
      'selectLanguage': 'Pilih Bahasa Aplikasi',
      'themeSelection': 'PILIHAN TEMA',
      'feedbackSettings': 'SUARA & GETARAN',
      'usageSettings': 'PREFERENSI PENGGUNAAN',
      'vibrationStrength': 'Kekuatan Getaran',
      'clickSound': 'Suara Klik',
      'milestoneVib': 'Getaran Saat Target Tercapai',
      'fullscreenMode': 'Mode Sentuh Layar Penuh',
      'privacyPolicy': 'Kebijakan Privasi',
      'about': 'Tentang & Versi',
      'virtueAndMeaning': 'Keutamaan & Arti',
      'meaning': 'Arti:',
      'virtue': 'Keutamaan:',
      'notSpecified': 'Tidak ditentukan',
      'tapForDetails': 'Ketuk untuk detail',
      'noDataForDate': 'Tidak ada zikir tercatat pada tanggal ini.',
      'totalDhikrOnDate': 'Sebanyak {count} zikir dilakukan pada tanggal ini.',
      'deleteConfirm': 'Apakah Anda yakin ingin menghapus zikir "{name}"?',
      'themeEmerald': 'Zamrud',
      'themeMidnight': 'Malam',
      'themeGold': 'Emas',
      'themeStone': 'Batu',
      'vibOff': 'Mati',
      'vibLight': 'Ringan',
      'vibMedium': 'Sedang',
      'vibStrong': 'Kuat',
      'change': 'Ubah',
      'close': 'Tutup',
      'ok': 'Oke',
      'aboutDesc': 'Aplikasi tasbih digital modern dan menenangkan hati.',
      'privacyContent': 'Aplikasi ini sepenuhnya menghormati privasi Anda. Tidak ada data pribadi yang dikumpulkan dan bekerja 100% offline.',
      // Dhikrs
      'dhikr_subhanallah_title': 'SubhanAllah',
      'dhikr_subhanallah_meaning': 'Maha Suci Allah dari segala kekurangan.',
      'dhikr_subhanallah_virtue': 'Dibaca 33 kali setelah shalat menggugurkan dosa sebanyak buih di lautan.',
      'dhikr_elhamdulillah_title': 'Alhamdulillah',
      'dhikr_elhamdulillah_meaning': 'Segala puji hanya bagi Allah semesta alam.',
      'dhikr_elhamdulillah_virtue': 'Alhamdulillah memenuhi timbangan amal kebaikan.',
      'dhikr_allahu_ekber_title': 'Allahu Akbar',
      'dhikr_allahu_ekber_meaning': 'Allah Maha Besar melampaui segalanya.',
      'dhikr_allahu_ekber_virtue': 'Menghilangkan kegelisahan hati dan menguatkan jiwa.',
      'dhikr_kelime_i_tevhid_title': 'La ilaha illallah',
      'dhikr_kelime_i_tevhid_meaning': 'Tiada Tuhan selain Allah.',
      'dhikr_kelime_i_tevhid_virtue': 'Sebaik-baik zikir dan kunci menuju surga.',
      'dhikr_estagfirullah_title': 'Astaghfirullahal \'Azhim',
      'dhikr_estagfirullah_meaning': 'Aku memohon ampun kepada Allah Yang Maha Agung.',
      'dhikr_estagfirullah_virtue': 'Membuka pintu rezeki dan menghapus noda dosa di hati.',
      'dhikr_salavat_title': 'Shalawat Nabi',
      'dhikr_salavat_meaning': 'Ya Allah limpahkanlah rahmat dan salam kepada Nabi Muhammad.',
      'dhikr_salavat_virtue': 'Satu kali bershalawat dibalas sepuluh rahmat oleh Allah.',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'Subhanallahi wa Bihamdihi',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'Maha Suci Allah dan segala puji bagi-Nya.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': '100 kali sehari menghapus dosa-dosa kecil.',
      'dhikr_la_havle_title': 'La Hawla wa La Quwwata illa Billah',
      'dhikr_la_havle_meaning': 'Tiada daya dan kekuatan kecuali dengan pertolongan Allah.',
      'dhikr_la_havle_virtue': 'Salah satu perbendaharaan surga dan penawar kegundahan.',
      'dhikr_hasbunallah_title': 'Hasbunallahu wa Ni\'mal Wakeel',
      'dhikr_hasbunallah_meaning': 'Cukuplah Allah bagi kami dan Dia sebaik-baik pelindung.',
      'dhikr_hasbunallah_virtue': 'Doa Nabi Ibrahim AS saat dilempar ke dalam api.',
      'dhikr_ya_allah_title': 'Ya Allah (Jalla Jalaluh)',
      'dhikr_ya_allah_meaning': 'Nama teragung yang mencakup seluruh sifat Ilahi.',
      'dhikr_ya_allah_virtue': 'Menerangi hati dengan ketenangan batin.',
    },

    // ----------------------------------------------------
    // 6. MALAYCA (ms)
    // ----------------------------------------------------
    'ms': {
      'appName': 'Tasbih Ketenangan',
      'tabCounter': 'Kira',
      'tabDhikrs': 'Zikir',
      'tabHistory': 'Sejarah',
      'tabSettings': 'Tetapan',
      'press': 'TEKAN',
      'goal': 'SASARAN',
      'free': 'BEBAS',
      'fullscreenOn': 'Skrin Penuh Hidup',
      'fullscreenOff': 'Skrin Penuh Mati',
      'undo': 'Undur 1',
      'reset': 'Set Semula',
      'sound': 'Bunyi',
      'vibration': 'Getaran',
      'today': 'Hari Ini',
      'total': 'Jumlah',
      'dailyActivity': 'Prestasi Mingguan',
      'dayBreakdownTitle': 'Pecahan Zikir Harian',
      'dayTotal': 'Jumlah Zikir',
      'topDhikrs': 'Zikir Paling Kerap',
      'allCategories': 'Semua',
      'prayerTesbihat': 'Wirid Solat',
      'dailyDhikrCat': 'Zikir Harian',
      'esmaulHusna': 'Asmaul Husna',
      'customDhikrsCat': 'Zikir Sendiri',
      'importantPrayers': 'Doa Utama',
      'addCustomDhikr': 'Tambah Zikir Baharu',
      'titleLabel': 'Tajuk Zikir *',
      'arabicLabel': 'Teks Arab',
      'targetLabel': 'Sasaran Bilangan',
      'meaningLabel': 'Maksud / Nota',
      'addAndSelect': 'Tambah & Pilih',
      'cancel': 'Batal',
      'delete': 'Padam',
      'congratulations': 'Tahniah! MasyaAllah',
      'targetReached': 'Anda telah menyempurnakan zikir ini. Semoga Allah menerimanya.',
      'continueBtn': 'Teruskan',
      'resetConfirmTitle': 'Set Semula Pengira',
      'resetConfirmBody': 'Adakah anda pasti mahu menetapkan semula pengira ini?',
      'language': 'Bahasa',
      'selectLanguage': 'Pilih Bahasa Aplikasi',
      'themeSelection': 'PILIHAN TEMA',
      'feedbackSettings': 'BUNYI & GETARAN',
      'usageSettings': 'KEUTAMAAN PENGGUNAAN',
      'vibrationStrength': 'Kekuatan Getaran',
      'clickSound': 'Bunyi Klik',
      'milestoneVib': 'Getaran Apabila Sasaran Tercapai',
      'fullscreenMode': 'Sentuhan Skrin Penuh',
      'privacyPolicy': 'Dasar Privasi',
      'about': 'Tentang Aplikasi',
      'virtueAndMeaning': 'Fadhilat dan Maksud',
      'meaning': 'Maksud:',
      'virtue': 'Fadhilat:',
      'notSpecified': 'Tidak dinyatakan',
      'tapForDetails': 'Ketik untuk maklumat',
      'noDataForDate': 'Tiada zikir direkodkan pada tarikh ini.',
      'totalDhikrOnDate': 'Sebanyak {count} zikir dilakukan pada hari ini.',
      'deleteConfirm': 'Adakah anda pasti mahu memadamkan "{name}"?',
      'themeEmerald': 'Zamrud',
      'themeMidnight': 'Malam',
      'themeGold': 'Emas',
      'themeStone': 'Batu',
      'vibOff': 'Tutup',
      'vibLight': 'Ringan',
      'vibMedium': 'Sederhana',
      'vibStrong': 'Kuat',
      'change': 'Tukar',
      'close': 'Tutup',
      'ok': 'OK',
      'aboutDesc': 'Aplikasi tasbih digital moden dan menenangkan jiwa.',
      'privacyContent': 'Aplikasi ini menghormati privasi anda. Tiada data dikumpulkan dan ia berfungsi 100% luar talian.',
      // Dhikrs
      'dhikr_subhanallah_title': 'SubhanAllah',
      'dhikr_subhanallah_meaning': 'Maha Suci Allah dari segala kelemahan.',
      'dhikr_subhanallah_virtue': 'Dibaca 33 kali selepas solat diampunkan dosa walau sebanyak buih di lautan.',
      'dhikr_elhamdulillah_title': 'Alhamdulillah',
      'dhikr_elhamdulillah_meaning': 'Segala puji bagi Allah.',
      'dhikr_elhamdulillah_virtue': 'Alhamdulillah memenuhi timbangan mizan.',
      'dhikr_allahu_ekber_title': 'Allahu Akbar',
      'dhikr_allahu_ekber_meaning': 'Allah Maha Besar mengatasi segalanya.',
      'dhikr_allahu_ekber_virtue': 'Menenangkan fikiran dan menghilangkan keraguan.',
      'dhikr_kelime_i_tevhid_title': 'La ilaha illallah',
      'dhikr_kelime_i_tevhid_meaning': 'Tiada Tuhan selain Allah.',
      'dhikr_kelime_i_tevhid_virtue': 'Sebaik-baik ucapan zikir dan kunci syurga.',
      'dhikr_estagfirullah_title': 'Astaghfirullahal \'Azhim',
      'dhikr_estagfirullah_meaning': 'Aku memohon keampunan kepada Allah Yang Maha Agung.',
      'dhikr_estagfirullah_virtue': 'Melapangkan rezeki dan membersihkan hati nurani.',
      'dhikr_salavat_title': 'Selawat ke atas Nabi',
      'dhikr_salavat_meaning': 'Ya Allah kurniakanlah selawat dan salam buat junjungan Nabi Muhammad.',
      'dhikr_salavat_virtue': 'Satu selawat dibalas sepuluh rahmat dari Allah.',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'Subhanallahi wa Bihamdihi',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'Maha Suci Allah dan segala puji untuk-Nya.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': '100 kali sehari menghapuskan dosa-dosa kecil.',
      'dhikr_la_havle_title': 'La Hawla wa La Quwwata illa Billah',
      'dhikr_la_havle_meaning': 'Tiada daya dan kekuatan melainkan dengan izin Allah.',
      'dhikr_la_havle_virtue': 'Khazanah daripada khazanah syurga pembuka jalan keluar.',
      'dhikr_hasbunallah_title': 'Hasbunallahu wa Ni\'mal Wakeel',
      'dhikr_hasbunallah_meaning': 'Cukuplah Allah bagi kami dan Dia sebaik-baik pelindung.',
      'dhikr_hasbunallah_virtue': 'Doa Nabi Ibrahim AS semasa dalam kesukaran yang genting.',
      'dhikr_ya_allah_title': 'Ya Allah (Jalla Jalaluh)',
      'dhikr_ya_allah_meaning': 'Nama teragung Yang Maha Esa.',
      'dhikr_ya_allah_virtue': 'Menerangi hati dan menguatkan keimanan.',
    },

    // ----------------------------------------------------
    // 7. FARSÇA (fa)
    // ----------------------------------------------------
    'fa': {
      'appName': 'تسبیح آرامش',
      'tabCounter': 'شمارنده',
      'tabDhikrs': 'اذکار',
      'tabHistory': 'پیشینه',
      'tabSettings': 'تنظیمات',
      'press': 'لمس',
      'goal': 'هدف',
      'free': 'آزاد',
      'fullscreenOn': 'تمام صفحه روشن',
      'fullscreenOff': 'تمام صفحه خاموش',
      'undo': 'یکی کم کن',
      'reset': 'بازنشانی',
      'sound': 'صدا',
      'vibration': 'لرزش',
      'today': 'امروز',
      'total': 'مجموع',
      'dailyActivity': 'فعالیت هفتگی',
      'dayBreakdownTitle': 'جزئیات ذکر روزانه',
      'dayTotal': 'مجموع اذکار',
      'topDhikrs': 'پرشمارترین اذکار',
      'allCategories': 'همه',
      'prayerTesbihat': 'تسبیحات نماز',
      'dailyDhikrCat': 'اذکار روزانه',
      'esmaulHusna': 'اسمای حسنی',
      'customDhikrsCat': 'اذکار شخصی',
      'importantPrayers': 'دعاهای مهم',
      'addCustomDhikr': 'افزودن ذکر جدید',
      'titleLabel': 'عنوان ذکر *',
      'arabicLabel': 'متن عربی',
      'targetLabel': 'تعداد هدف',
      'meaningLabel': 'معنی یا یادداشت',
      'addAndSelect': 'افزودن و انتخاب',
      'cancel': 'انصراف',
      'delete': 'حذف',
      'congratulations': 'ماشاءالله! تبریک',
      'targetReached': 'ذکر به هدف تعیین شده رسید. طاعات شما قبول درگاه حق.',
      'continueBtn': 'ادامه',
      'resetConfirmTitle': 'صفر کردن شمارنده',
      'resetConfirmBody': 'آیا مایل به بازنشانی شمارنده فعلی هستید؟',
      'language': 'زبان برنامه',
      'selectLanguage': 'انتخاب زبان',
      'themeSelection': 'انتخاب تم',
      'feedbackSettings': 'صدا و لرزش',
      'usageSettings': 'ترجیحات کاربری',
      'vibrationStrength': 'شدت لرزش',
      'clickSound': 'صدای کلیک',
      'milestoneVib': 'لرزش در پایان هدف',
      'fullscreenMode': 'حالت لمس تمام صفحه',
      'privacyPolicy': 'حریم خصوصی',
      'about': 'درباره برنامه',
      'virtueAndMeaning': 'فضیلت و معنی',
      'meaning': 'معنی:',
      'virtue': 'فضیلت:',
      'notSpecified': 'مشخص نشده',
      'tapForDetails': 'برای جزئیات ضربه بزنید',
      'noDataForDate': 'هیچ ذکری در این تاریخ ثبت نشده است.',
      'totalDhikrOnDate': 'در این تاریخ مجموعاً {count} ذکر ثبت شد.',
      'deleteConfirm': 'آیا از حذف ذکر "{name}" مطمئن هستید؟',
      'themeEmerald': 'زمرد',
      'themeMidnight': 'شب',
      'themeGold': 'طلا',
      'themeStone': 'سنگ',
      'vibOff': 'خاموش',
      'vibLight': 'ملایم',
      'vibMedium': 'متوسط',
      'vibStrong': 'قوی',
      'change': 'تغییر',
      'close': 'بستن',
      'ok': 'تأیید',
      'aboutDesc': 'برنامه تسبیح و صلوات شمار دیجیتال مدرن و آرامش بخش.',
      'privacyContent': 'این برنامه کاملاً به حریم خصوصی شما احترام می‌گذارد و بدون نیاز به اینترنت آفلاین کار می‌کند.',
      // Dhikrs
      'dhikr_subhanallah_title': 'سبحان الله',
      'dhikr_subhanallah_meaning': 'خداوند از هر گونه نقص و عیبی پاک و منزه است.',
      'dhikr_subhanallah_virtue': 'گفتن ۳۳ مرتبه بعد از نماز مایه آمرزش گناهان است.',
      'dhikr_elhamdulillah_title': 'الحمد لله',
      'dhikr_elhamdulillah_meaning': 'همه ستایش‌ها تنها مخصوص پروردگار است.',
      'dhikr_elhamdulillah_virtue': 'الحمدلله ترازوی عمل را پر می‌کند.',
      'dhikr_allahu_ekber_title': 'الله اکبر',
      'dhikr_allahu_ekber_meaning': 'خداوند بزرگتر از آن است که توصیف شود.',
      'dhikr_allahu_ekber_virtue': 'آرامش بخش دل‌ها و دور کننده اضطراب.',
      'dhikr_kelime_i_tevhid_title': 'لا اله الا الله',
      'dhikr_kelime_i_tevhid_meaning': 'هیچ خدایی جز خدای یگانه نیست.',
      'dhikr_kelime_i_tevhid_virtue': 'برترین ذکر و کلید بهشت.',
      'dhikr_estagfirullah_title': 'استغفر الله العظیم',
      'dhikr_estagfirullah_meaning': 'از خداوند بزرگ طلب بخشش و مغفرت می‌کنم.',
      'dhikr_estagfirullah_virtue': 'گشایش روزی و زدودن غم و اندوه.',
      'dhikr_salavat_title': 'صلوات بر پیامبر',
      'dhikr_salavat_meaning': 'خدایا بر محمد و خاندان پاکش درود فرست.',
      'dhikr_salavat_virtue': 'هر صلوات ده برابر رحمت الهی به همراه دارد.',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'سبحان الله وبحمده',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'منزه است خدا و او را سپاس می‌گویم.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': '۱۰۰ مرتبه در روز گناهان را محو می‌کند.',
      'dhikr_la_havle_title': 'لا حول ولا قوة الا بالله',
      'dhikr_la_havle_meaning': 'هیچ قدرت و توانی جز به خواست خداوند نیست.',
      'dhikr_la_havle_virtue': 'گنجی از گنج‌های بهشت و برطرف‌کننده گرفتاری‌ها.',
      'dhikr_hasbunallah_title': 'حسبنا الله ونعم الوکیل',
      'dhikr_hasbunallah_meaning': 'خدا ما را بس است و او بهترین پشتیبان است.',
      'dhikr_hasbunallah_virtue': 'پناهگاه امن مؤمن در سختی‌ها و ترس‌ها.',
      'dhikr_ya_allah_title': 'یا الله (جل جلاله)',
      'dhikr_ya_allah_meaning': 'اسم اعظم پروردگار که جامع تمام صفات است.',
      'dhikr_ya_allah_virtue': 'روشنی‌بخش قلب و افزایش‌دهنده معرفت.',
    },

    // ----------------------------------------------------
    // 8. RUSÇA (ru)
    // ----------------------------------------------------
    'ru': {
      'appName': 'Тасбих Спокойствия',
      'tabCounter': 'Счётчик',
      'tabDhikrs': 'Зикры',
      'tabHistory': 'История',
      'tabSettings': 'Настройки',
      'press': 'НАЖМИ',
      'goal': 'ЦЕЛЬ',
      'free': 'СВОБОДНО',
      'fullscreenOn': 'Весь экран вкл',
      'fullscreenOff': 'Весь экран выкл',
      'undo': '-1 Назад',
      'reset': 'Сброс',
      'sound': 'Звук',
      'vibration': 'Вибрация',
      'today': 'Сегодня',
      'total': 'Всего',
      'dailyActivity': 'Недельная активность',
      'dayBreakdownTitle': 'Детали зикров за день',
      'dayTotal': 'Всего зикров',
      'topDhikrs': 'Часто читаемые зикры',
      'allCategories': 'Все',
      'prayerTesbihat': 'Молитвенный тасбих',
      'dailyDhikrCat': 'Ежедневные зикры',
      'esmaulHusna': 'Имена Аллаха',
      'customDhikrsCat': 'Мои зикры',
      'importantPrayers': 'Важные дуа',
      'addCustomDhikr': 'Добавить новый зикр',
      'titleLabel': 'Название зикра *',
      'arabicLabel': 'Арабский текст (необязательно)',
      'targetLabel': 'Целевое число',
      'meaningLabel': 'Значение / Заметки',
      'addAndSelect': 'Добавить и выбрать',
      'cancel': 'Отмена',
      'delete': 'Удалить',
      'congratulations': 'МашаАллах! Поздравляем',
      'targetReached': 'Вы успешно выполнили цель этого зикра. Да примет Аллах.',
      'continueBtn': 'Продолжить',
      'resetConfirmTitle': 'Сбросить счётчик',
      'resetConfirmBody': 'Вы действительно хотите сбросить текущий счётчик? Общее количество сохраняется.',
      'language': 'Язык приложения',
      'selectLanguage': 'Выберите язык',
      'themeSelection': 'ВЫБОР ТЕМЫ',
      'feedbackSettings': 'ЗВУК И ВИБРАЦИЯ',
      'usageSettings': 'ПАРАМЕТРЫ ИСПОЛЬЗОВАНИЯ',
      'vibrationStrength': 'Сила вибрации',
      'clickSound': 'Звук клика',
      'milestoneVib': 'Вибрация при достижении цели',
      'fullscreenMode': 'Касание по всему экрану',
      'privacyPolicy': 'Политика конфиденциальности',
      'about': 'О приложении и версия',
      'virtueAndMeaning': 'Достоинство и смысл',
      'meaning': 'Смысл:',
      'virtue': 'Достоинство:',
      'notSpecified': 'Не указано',
      'tapForDetails': 'Нажмите для деталей',
      'noDataForDate': 'На эту дату записей нет.',
      'totalDhikrOnDate': 'В этот день совершено {count} зикров.',
      'deleteConfirm': 'Вы уверены, что хотите удалить зикр "{name}"?',
      'themeEmerald': 'Изумруд',
      'themeMidnight': 'Полночь',
      'themeGold': 'Золото',
      'themeStone': 'Камень',
      'vibOff': 'Выкл',
      'vibLight': 'Легкая',
      'vibMedium': 'Средняя',
      'vibStrong': 'Сильная',
      'change': 'Изменить',
      'close': 'Закрыть',
      'ok': 'ОК',
      'aboutDesc': 'Современный, минималистичный цифровой электронный тасбих.',
      'privacyContent': 'Приложение полностью уважает вашу конфиденциальность. Никакие личные данные не собираются, работает 100% офлайн.',
      // Dhikrs
      'dhikr_subhanallah_title': 'Субханаллах',
      'dhikr_subhanallah_meaning': 'Пречист Аллах от любых недостатков.',
      'dhikr_subhanallah_virtue': 'Произнесение 33 раза после намаза смывает грехи, даже если их столько, сколько морской пены.',
      'dhikr_elhamdulillah_title': 'Альхамдулиллях',
      'dhikr_elhamdulillah_meaning': 'Вся хвала принадлежит только Аллаху.',
      'dhikr_elhamdulillah_virtue': 'Альхамдулиллях наполняет Чашу весов благими делами.',
      'dhikr_allahu_ekber_title': 'Аллаху Акбар',
      'dhikr_allahu_ekber_meaning': 'Аллах Превелик, выше всего сущего.',
      'dhikr_allahu_ekber_virtue': 'Прогоняет сомнения и наполняет сердце величием Творца.',
      'dhikr_kelime_i_tevhid_title': 'Ля иляха илляллах',
      'dhikr_kelime_i_tevhid_meaning': 'Нет божества, кроме Единого Аллаха.',
      'dhikr_kelime_i_tevhid_virtue': 'Наилучший зикр, основа веры и ключ от Рая.',
      'dhikr_estagfirullah_title': 'Астагфируллах Аль-Азым',
      'dhikr_estagfirullah_meaning': 'Прошу прощения у Великого Аллаха.',
      'dhikr_estagfirullah_virtue': 'Дарует пропитание, избавляет от печалей и очищает сердце.',
      'dhikr_salavat_title': 'Салават Пророку',
      'dhikr_salavat_meaning': 'О Аллах, благослови Мухаммада и род его.',
      'dhikr_salavat_virtue': 'Кто один раз благословит Пророка, того Аллах благословит десять раз.',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'Субханаллахи ва Бихамдихи',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'Слава Аллаху и хвала Ему.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': '100 раз в день стирают мелкие прегрешения.',
      'dhikr_la_havle_title': 'Ля хавля ва ля куввата илля биллях',
      'dhikr_la_havle_meaning': 'Нет силы и мощи ни у кого, кроме Аллаха.',
      'dhikr_la_havle_virtue': 'Сокровище из сокровищниц Рая и исцеление от тревог.',
      'dhikr_hasbunallah_title': 'Хасбуналлаху ва ни\'маль вакиль',
      'dhikr_hasbunallah_meaning': 'Нам достаточен Аллах, и Он — лучший Покровитель.',
      'dhikr_hasbunallah_virtue': 'Слова пророка Ибрахима (а.с.) в час испытания огнем.',
      'dhikr_ya_allah_title': 'Йа Аллах (Джалла Джалялуху)',
      'dhikr_ya_allah_meaning': 'Величайшее имя, объединяющее все божественные атрибуты.',
      'dhikr_ya_allah_virtue': 'Освещает сердце верой и дарует проницательность.',
    },

    // ----------------------------------------------------
    // 9. FRANSIZCA (fr)
    // ----------------------------------------------------
    'fr': {
      'appName': 'Sérénité Tasbih',
      'tabCounter': 'Compteur',
      'tabDhikrs': 'Dhikrs',
      'tabHistory': 'Historique',
      'tabSettings': 'Paramètres',
      'press': 'TAP',
      'goal': 'OBJECTIF',
      'free': 'LIBRE',
      'fullscreenOn': 'Plein écran activé',
      'fullscreenOff': 'Plein écran désactivé',
      'undo': '-1 Diminuer',
      'reset': 'Réinitialiser',
      'sound': 'Son',
      'vibration': 'Vibration',
      'today': 'Aujourd\'hui',
      'total': 'Total',
      'dailyActivity': 'Régularité hebdomadaire',
      'dayBreakdownTitle': 'Détail des dhikrs du jour',
      'dayTotal': 'Total des invocations',
      'topDhikrs': 'Dhikrs les plus récités',
      'allCategories': 'Tous',
      'prayerTesbihat': 'Tasbih de prière',
      'dailyDhikrCat': 'Dhikrs quotidiens',
      'esmaulHusna': 'Les Noms d\'Allah',
      'customDhikrsCat': 'Mes Dhikrs',
      'importantPrayers': 'Invocations clés',
      'addCustomDhikr': 'Ajouter un dhikr',
      'titleLabel': 'Titre du dhikr *',
      'arabicLabel': 'Texte en arabe (optionnel)',
      'targetLabel': 'Nombre cible',
      'meaningLabel': 'Sens / Remarques',
      'addAndSelect': 'Ajouter et choisir',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'congratulations': 'MashaAllah ! Félicitations',
      'targetReached': 'Vous avez atteint votre objectif pour cette invocation. Qu\'Allah accepte.',
      'continueBtn': 'Continuer',
      'resetConfirmTitle': 'Remise à zéro',
      'resetConfirmBody': 'Voulez-vous réinitialiser le compteur actuel ? Le total à vie reste conservé.',
      'language': 'Langue',
      'selectLanguage': 'Choisir la langue de l\'application',
      'themeSelection': 'CHOIX DU THÈME',
      'feedbackSettings': 'RETOUR & SENSATIONS',
      'usageSettings': 'PRÉFÉRENCES',
      'vibrationStrength': 'Intensité de vibration',
      'clickSound': 'Effet sonore de clic',
      'milestoneVib': 'Vibration à l\'objectif atteint',
      'fullscreenMode': 'Mode tactile plein écran',
      'privacyPolicy': 'Politique de confidentialité',
      'about': 'À propos & Version',
      'virtueAndMeaning': 'Mérite et signification',
      'meaning': 'Sens :',
      'virtue': 'Mérite :',
      'notSpecified': 'Non spécifié',
      'tapForDetails': 'Appuyer pour détails',
      'noDataForDate': 'Aucun dhikr enregistré pour cette date.',
      'totalDhikrOnDate': 'Un total de {count} dhikrs a été effectué ce jour.',
      'deleteConfirm': 'Voulez-vous vraiment supprimer "{name}" ?',
      'themeEmerald': 'Émeraude',
      'themeMidnight': 'Nuit',
      'themeGold': 'Or',
      'themeStone': 'Pierre',
      'vibOff': 'Désactivé',
      'vibLight': 'Léger',
      'vibMedium': 'Moyen',
      'vibStrong': 'Fort',
      'change': 'Changer',
      'close': 'Fermer',
      'ok': 'D\'accord',
      'aboutDesc': 'Application de tasbih numérique islamique élégante et sereine.',
      'privacyContent': 'Cette application respecte rigoureusement votre vie privée. Aucune donnée n\'est collectée et fonctionne à 100% hors ligne.',
      // Dhikrs
      'dhikr_subhanallah_title': 'SubhanAllah',
      'dhikr_subhanallah_meaning': 'Gloire et pureté à Allah, exempt de toute imperfection.',
      'dhikr_subhanallah_virtue': 'Récité 33 fois après la prière, efface les péchés même nombreux comme l\'écume de mer.',
      'dhikr_elhamdulillah_title': 'Alhamdulillah',
      'dhikr_elhamdulillah_meaning': 'Toutes les louanges et la gratitude n\'appartiennent qu\'à Allah.',
      'dhikr_elhamdulillah_virtue': 'Alhamdulillah remplit la Balance des bonnes actions.',
      'dhikr_allahu_ekber_title': 'Allahu Akbar',
      'dhikr_allahu_ekber_meaning': 'Allah est le Plus Grand, au-dessus de toute chose.',
      'dhikr_allahu_ekber_virtue': 'Chasse les doutes du cœur et installe la paix spirituelle.',
      'dhikr_kelime_i_tevhid_title': 'La ilaha illallah',
      'dhikr_kelime_i_tevhid_meaning': 'Il n\'y a de divinité digne d\'adoration qu\'Allah seul.',
      'dhikr_kelime_i_tevhid_virtue': 'La meilleure des invocations, clé du Paradis et fondement de la foi.',
      'dhikr_estagfirullah_title': 'Astaghfirullah Al-Azim',
      'dhikr_estagfirullah_meaning': 'Je demande pardon à Allah le Tout-Puissant.',
      'dhikr_estagfirullah_virtue': 'Apporte la subsistance, apaise les soucis et purifie le cœur.',
      'dhikr_salavat_title': 'Salawat sur le Prophète',
      'dhikr_salavat_meaning': 'Ô Allah ! Répands Tes bénédictions et Ta paix sur notre maître Muhammad.',
      'dhikr_salavat_virtue': 'Celui qui prie sur moi une fois, Allah le bénit dix fois.',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'SubhanAllahi wa Bihamdihi',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'Gloire à Allah et louange à Lui.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': 'Répété 100 fois par jour, les péchés sont pardonnés.',
      'dhikr_la_havle_title': 'La Hawla wa La Quwwata illa Billah',
      'dhikr_la_havle_meaning': 'Il n\'y a de force ni de puissance que par Allah.',
      'dhikr_la_havle_virtue': 'Un trésor parmi les trésors du Paradis.',
      'dhikr_hasbunallah_title': 'Hasbunallahu wa Ni\'mal Wakeel',
      'dhikr_hasbunallah_meaning': 'Allah nous suffit, et Il est le meilleur Garant.',
      'dhikr_hasbunallah_virtue': 'Parole du Prophète Ibrahim face à l\'épreuve du feu.',
      'dhikr_ya_allah_title': 'Ya Allah (Jalla Jalaluh)',
      'dhikr_ya_allah_meaning': 'Le Nom Suprême qui englobe tous les attributs divins.',
      'dhikr_ya_allah_virtue': 'Illumine l\'âme et renforce la certitude intérieure.',
    },

    // ----------------------------------------------------
    // 10. ALMANCA (de)
    // ----------------------------------------------------
    'de': {
      'appName': 'Seelenfrieden Tasbih',
      'tabCounter': 'Zähler',
      'tabDhikrs': 'Dhikr',
      'tabHistory': 'Verlauf',
      'tabSettings': 'Optionen',
      'press': 'DRÜCKEN',
      'goal': 'ZIEL',
      'free': 'FREI',
      'fullscreenOn': 'Vollbild Ein',
      'fullscreenOff': 'Vollbild Aus',
      'undo': '-1 Zähler',
      'reset': 'Zurücksetzen',
      'sound': 'Ton',
      'vibration': 'Vibration',
      'today': 'Heute',
      'total': 'Gesamt',
      'dailyActivity': 'Wöchentliche Aktivität',
      'dayBreakdownTitle': 'Tages-Dhikr-Übersicht',
      'dayTotal': 'Gesamte Dhikr',
      'topDhikrs': 'Meistrezitierte Dhikr',
      'allCategories': 'Alle',
      'prayerTesbihat': 'Gebetstasbih',
      'dailyDhikrCat': 'Tägliche Dhikr',
      'esmaulHusna': 'Namen Allahs',
      'customDhikrsCat': 'Eigene Dhikr',
      'importantPrayers': 'Wichtige Bittgebete',
      'addCustomDhikr': 'Neuen Dhikr hinzufügen',
      'titleLabel': 'Dhikr-Titel *',
      'arabicLabel': 'Arabischer Text (optional)',
      'targetLabel': 'Zielanzahl',
      'meaningLabel': 'Bedeutung / Notizen',
      'addAndSelect': 'Hinzufügen & Wählen',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'congratulations': 'MaschaAllah! Herzlichen Glückwunsch',
      'targetReached': 'Sie haben das Ziel für diesen Dhikr erreicht. Möge Allah es annehmen.',
      'continueBtn': 'Fortfahren',
      'resetConfirmTitle': 'Zähler zurücksetzen',
      'resetConfirmBody': 'Möchten Sie den Zähler zurücksetzen? Die Gesamtsumme bleibt erhalten.',
      'language': 'Sprachauswahl',
      'selectLanguage': 'App-Sprache auswählen',
      'themeSelection': 'THEMENAUSWAHL',
      'feedbackSettings': 'FEEDBACK & TÖNE',
      'usageSettings': 'NUTZUNGSOPTIONEN',
      'vibrationStrength': 'Vibrationsstärke',
      'clickSound': 'Klickgeräusch',
      'milestoneVib': 'Vibration bei Zielerreichung',
      'fullscreenMode': 'Vollbild-Tipp-Modus',
      'privacyPolicy': 'Datenschutzbestimmungen',
      'about': 'Über die App & Version',
      'virtueAndMeaning': 'Vorzug und Bedeutung',
      'meaning': 'Bedeutung:',
      'virtue': 'Vorzug:',
      'notSpecified': 'Nicht angegeben',
      'tapForDetails': 'Tippen für Details',
      'noDataForDate': 'Keine Einträge für dieses Datum vorhanden.',
      'totalDhikrOnDate': 'Insgesamt wurden {count} Dhikr an diesem Tag rezitiert.',
      'deleteConfirm': 'Möchten Sie "{name}" wirklich löschen?',
      'themeEmerald': 'Smaragd',
      'themeMidnight': 'Mitternacht',
      'themeGold': 'Gold',
      'themeStone': 'Stein',
      'vibOff': 'Aus',
      'vibLight': 'Leicht',
      'vibMedium': 'Mittel',
      'vibStrong': 'Stark',
      'change': 'Ändern',
      'close': 'Schließen',
      'ok': 'OK',
      'aboutDesc': 'Moderne, minimalistische und beruhigende digitale Tasbih-App.',
      'privacyContent': 'Diese App respektiert Ihre Privatsphäre absolut. Es werden keine Daten erhoben und sie funktioniert zu 100% offline.',
      // Dhikrs
      'dhikr_subhanallah_title': 'SubhanAllah',
      'dhikr_subhanallah_meaning': 'Gepriesen sei Allah, fern von allen Mängeln.',
      'dhikr_subhanallah_virtue': '33-mal nach dem Gebet gesprochen vergibt Sünden wie Schaum auf dem Meer.',
      'dhikr_elhamdulillah_title': 'Alhamdulillah',
      'dhikr_elhamdulillah_meaning': 'Alles Lob gebührt allein Allah.',
      'dhikr_elhamdulillah_virtue': 'Alhamdulillah füllt die Waage guter Taten.',
      'dhikr_allahu_ekber_title': 'Allahu Akbar',
      'dhikr_allahu_ekber_meaning': 'Allah ist der Größte über allem.',
      'dhikr_allahu_ekber_virtue': 'Vertreibt Unruhe aus dem Herzen und schenkt Gottesfurcht.',
      'dhikr_kelime_i_tevhid_title': 'La ilaha illallah',
      'dhikr_kelime_i_tevhid_meaning': 'Es gibt keinen Gott außer Allah.',
      'dhikr_kelime_i_tevhid_virtue': 'Der vorzüglichste Dhikr, Schlüssel zum Paradies.',
      'dhikr_estagfirullah_title': 'Astaghfirullah Al-Azim',
      'dhikr_estagfirullah_meaning': 'Ich bitte Allah den Allmächtigen um Vergebung.',
      'dhikr_estagfirullah_virtue': 'Bringt Segen in den Lebensunterhalt und reinigt die Seele.',
      'dhikr_salavat_title': 'Segenswünsche auf den Propheten',
      'dhikr_salavat_meaning': 'O Allah, segne unseren Propheten Muhammad und schenke ihm Frieden.',
      'dhikr_salavat_virtue': 'Wer einmal segnet, den segnet Allah zehnfach.',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'SubhanAllahi wa Bihamdihi',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'Gepriesen sei Allah und Sein ist das Lob.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': '100-mal täglich löscht Sünden aus.',
      'dhikr_la_havle_title': 'La Hawla wa La Quwwata illa Billah',
      'dhikr_la_havle_meaning': 'Es gibt keine Macht noch Kraft außer durch Allah.',
      'dhikr_la_havle_virtue': 'Ein Schatz aus den Schätzen des Paradieses.',
      'dhikr_hasbunallah_title': 'Hasbunallahu wa Ni\'mal Wakeel',
      'dhikr_hasbunallah_meaning': 'Allah genügt uns, und Er ist der beste Sachwalter.',
      'dhikr_hasbunallah_virtue': 'Bittgebet des Propheten Ibrahim in Zeiten höchster Not.',
      'dhikr_ya_allah_title': 'Ya Allah (Jalla Jalaluhu)',
      'dhikr_ya_allah_meaning': 'Der erhabenste Name, der alle göttlichen Eigenschaften vereint.',
      'dhikr_ya_allah_virtue': 'Erhellt das Herz und stärkt die spirituelle Gewissheit.',
    },

    // ----------------------------------------------------
    // 11. İTALYANCA (it)
    // ----------------------------------------------------
    'it': {
      'appName': 'Serenità Tasbih',
      'tabCounter': 'Contatore',
      'tabDhikrs': 'Dhikr',
      'tabHistory': 'Storico',
      'tabSettings': 'Impostazioni',
      'press': 'PREMI',
      'goal': 'OBIETTIVO',
      'free': 'LIBERO',
      'fullscreenOn': 'Schermo intero attivo',
      'fullscreenOff': 'Schermo intero disattivato',
      'undo': '-1 Riduci',
      'reset': 'Azzera',
      'sound': 'Suono',
      'vibration': 'Vibrazione',
      'today': 'Oggi',
      'total': 'Totale',
      'dailyActivity': 'Costanza settimanale',
      'dayBreakdownTitle': 'Dettagli dhikr del giorno',
      'dayTotal': 'Totale invocazioni',
      'topDhikrs': 'Dhikr più recitati',
      'allCategories': 'Tutti',
      'prayerTesbihat': 'Tasbih della preghiera',
      'dailyDhikrCat': 'Dhikr quotidiani',
      'esmaulHusna': 'I Nomi di Allah',
      'customDhikrsCat': 'I miei Dhikr',
      'importantPrayers': 'Preghiere importanti',
      'addCustomDhikr': 'Aggiungi nuovo dhikr',
      'titleLabel': 'Titolo del dhikr *',
      'arabicLabel': 'Testo in arabo (opzionale)',
      'targetLabel': 'Conteggio obiettivo',
      'meaningLabel': 'Significato / Note',
      'addAndSelect': 'Aggiungi e seleziona',
      'cancel': 'Annulla',
      'delete': 'Elimina',
      'congratulations': 'MashaAllah! Congratulazioni',
      'targetReached': 'Hai raggiunto l\'obiettivo per questo dhikr. Che Allah accetti.',
      'continueBtn': 'Continua',
      'resetConfirmTitle': 'Azzera contatore',
      'resetConfirmBody': 'Sei sicuro di voler azzerare il contatore attuale? Il conteggio totale è conservato.',
      'language': 'Lingua',
      'selectLanguage': 'Seleziona lingua applicazione',
      'themeSelection': 'SCELTA DEL TEMA',
      'feedbackSettings': 'FEEDBACK E SUONI',
      'usageSettings': 'PREFERENZE D\'USO',
      'vibrationStrength': 'Intensità vibrazione',
      'clickSound': 'Effetto sonoro clic',
      'milestoneVib': 'Vibrazione al traguardo',
      'fullscreenMode': 'Tocco a schermo intero',
      'privacyPolicy': 'Informativa sulla privacy',
      'about': 'Info e versione',
      'virtueAndMeaning': 'Virtù e significato',
      'meaning': 'Significato:',
      'virtue': 'Virtù:',
      'notSpecified': 'Non specificato',
      'tapForDetails': 'Tocca per i dettagli',
      'noDataForDate': 'Nessun dhikr registrato in questa data.',
      'totalDhikrOnDate': 'Un totale di {count} dhikr eseguiti in questo giorno.',
      'deleteConfirm': 'Sei sicuro di voler eliminare "{name}"?',
      'themeEmerald': 'Smeraldo',
      'themeMidnight': 'Notte',
      'themeGold': 'Oro',
      'themeStone': 'Pietra',
      'vibOff': 'Spento',
      'vibLight': 'Leggera',
      'vibMedium': 'Media',
      'vibStrong': 'Forte',
      'change': 'Cambia',
      'close': 'Chiudi',
      'ok': 'OK',
      'aboutDesc': 'Applicazione tasbih digitale moderna, sobria e serena.',
      'privacyContent': 'Questa applicazione rispetta la tua privacy al 100%. Nessun dato personale viene raccolto e funziona interamente offline.',
      // Dhikrs
      'dhikr_subhanallah_title': 'SubhanAllah',
      'dhikr_subhanallah_meaning': 'Gloria ad Allah, libero da ogni imperfezione.',
      'dhikr_subhanallah_virtue': 'Recitato 33 volte dopo la preghiera cancella i peccati anche se pari alla schiuma del mare.',
      'dhikr_elhamdulillah_title': 'Alhamdulillah',
      'dhikr_elhamdulillah_meaning': 'Tutta la lode e la gratitudine appartengono solo ad Allah.',
      'dhikr_elhamdulillah_virtue': 'Alhamdulillah riempie la Bilancia delle buone azioni.',
      'dhikr_allahu_ekber_title': 'Allahu Akbar',
      'dhikr_allahu_ekber_meaning': 'Allah è il Più Grande sopra ogni cosa.',
      'dhikr_allahu_ekber_virtue': 'Scaccia i dubbi dal cuore e dona pace spirituale.',
      'dhikr_kelime_i_tevhid_title': 'La ilaha illallah',
      'dhikr_kelime_i_tevhid_meaning': 'Non vi è altro dio all\'infuori di Allah.',
      'dhikr_kelime_i_tevhid_virtue': 'La migliore delle invocazioni, chiave del Paradiso.',
      'dhikr_estagfirullah_title': 'Astaghfirullah Al-Azim',
      'dhikr_estagfirullah_meaning': 'Chiedo perdono ad Allah l\'Immenso.',
      'dhikr_estagfirullah_virtue': 'Allarga il sostentamento e purifica il cuore spirituale.',
      'dhikr_salavat_title': 'Salawat sul Profeta',
      'dhikr_salavat_meaning': 'O Allah, concedi pace e benedizioni al nostro Maestro Muhammad.',
      'dhikr_salavat_virtue': 'Chi invoca benedizioni su di me una volta, Allah lo benedice dieci volte.',
      'dhikr_subhanallahi_ve_bihamdihi_title': 'SubhanAllahi wa Bihamdihi',
      'dhikr_subhanallahi_ve_bihamdihi_meaning': 'Gloria ad Allah e a Lui sia la lode.',
      'dhikr_subhanallahi_ve_bihamdihi_virtue': '100 volte al giorno cancella le colpe minori.',
      'dhikr_la_havle_title': 'La Hawla wa La Quwwata illa Billah',
      'dhikr_la_havle_meaning': 'Non c\'è potere né forza se non in Allah.',
      'dhikr_la_havle_virtue': 'Un tesoro tra i tesori del Paradiso.',
      'dhikr_hasbunallah_title': 'Hasbunallahu wa Ni\'mal Wakeel',
      'dhikr_hasbunallah_meaning': 'Allah ci basta, ed Egli è il migliore dei Protettori.',
      'dhikr_hasbunallah_virtue': 'Invocazione del Profeta Abramo nel momento della prova.',
      'dhikr_ya_allah_title': 'Ya Allah (Jalla Jalaluh)',
      'dhikr_ya_allah_meaning': 'Il Nome Supremo che racchiude tutti gli attributi divini.',
      'dhikr_ya_allah_virtue': 'Illumina il cuore e dona profonda quiete interiore.',
    },
  };
}
